apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: payments
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: risk-compliance
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: customer
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: platform
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: security-tools
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: ingress-system
  labels:
    app.kubernetes.io/managed-by: platform-team
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
