apiVersion: v1
kind: ResourceQuota
metadata:
  name: payments-quota
  namespace: payments
spec:
  hard:
    requests.cpu: "60"
    requests.memory: 64Gi
    limits.cpu: "120"
    limits.memory: 128Gi
    pods: "140"
    services: "20"
    configmaps: "50"
    persistentvolumeclaims: "12"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: risk-compliance-quota
  namespace: risk-compliance
spec:
  hard:
    requests.cpu: "24"
    requests.memory: 32Gi
    limits.cpu: "36"
    limits.memory: 48Gi
    pods: "60"
    services: "20"
    configmaps: "50"
    persistentvolumeclaims: "12"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: customer-quota
  namespace: customer
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 28Gi
    limits.cpu: "32"
    limits.memory: 44Gi
    pods: "55"
    services: "20"
    configmaps: "50"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-quota
  namespace: platform
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 36Gi
    pods: "45"
    services: "20"
    configmaps: "60"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-tools-quota
  namespace: security-tools
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    pods: "40"
    services: "15"
    persistentvolumeclaims: "8"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ingress-system-quota
  namespace: ingress-system
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 16Gi
    pods: "30"
    services: "20"
